export const PAYMENTS_INVOICE_CHANGE = "PAYMENTS_INVOICE_CHANGE";
export const PAYMENTS_INVOICE_CREATE = "PAYMENTS_INVOICE_CREATE";
export const PAYMENTS_INVOICE_CREATE_SUCCESSFUL = "PAYMENTS_INVOICE_CREATE_SUCCESSFUL";
